 version: '3.0'
 services:
  mlflow:
      #image: /Dockerfile
      entrypoint: bash -c "mlflow server --backend-store-uri sqlite:///mlflow.db  --default-artifact-root s3://mlflow --host 0.0.0.0 "
      ports:
        - 5000:5000
      restart: always
      environment:
        MLFLOW_S3_ENDPOINT_URL: http://minio:9000
        AWS_ACCESS_KEY_ID: "ciao"
        AWS_SECRET_ACCESS_KEY: "ciao123456"
        #GUNICORN_CMD_ARGS: "--timeout 600"
        MLFLOW_TRACKING_URI: http://localhost:5000
        
      build:
        dockerfile: Dockerfile
      healthcheck:
        test: ["CMD", "curl", "--fail", "sqlite:///mlflow.db"]
        interval: 10s
        timeout: 10s
        retries: 5
      depends_on:
        - minio
        - fastapi 
  
  minio:
      image: minio/minio:latest
      working_dir: "/minio/storage"
      volumes:
          - ./mlflow-artifact-storage:/minio/storage
      ports:
          - "9000:9000"
          - "9001:9001"
      environment:
          MINIO_ROOT_USER: "ciao"
          MINIO_ROOT_PASSWORD: "ciao123456"
      command: server /minio/storage --console-address ":9001"
      restart: always
  fastapi:
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: "ciao"
      AWS_SECRET_ACCESS_KEY: "ciao123456"
      MLFLOW_TRACKING_URI: http://mlflow:5000
      #GUNICORN_CMD_ARGS: "timeout 600"
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    depends_on:
      - minio
      #- mlflow
    ports:
      - 8000:8000